In [ ]:
print("Hello")

In [ ]:
f = open('name.txt', 'r', encoding='utf-8')
data = f.read()

print(data)
f.close()

In [ ]:
f = open('name2.txt', 'w', encoding='utf-8')

while True :
    team = input() 

    if not team :
        break

    f.write(team + '\n')

f.close()

In [ ]:
%pip install pandas openpyxl

In [17]:
# 엑셀파일 입출력

import pandas as pd

df = pd.read_excel('my_grade.xlsx')

add_df = pd.DataFrame([{
    '이름' : '자룡',
    '1차지필' : 63,
    '2차지필' : 75,
    '수행1' : 84,
    '수행2' : 79,
    '등급' : 'C' 
}])

modi_file = pd.concat([df, add_df], ignore_index=True)
modi_file.to_excel('new_grade.xlsx', index=False)

modi_file

   이름  1차지필  2차지필  수행1  수행2 등급
0  유비    92    88   93   95  A
1  관우    89    90   85   78  B
2  장비    71    84   67   70  C
3  자룡    63    75   84   79  C

In [16]:
import pandas as pd

df = pd.read_excel('club.xlsx')

add_df = pd.DataFrame([{
    '학번' : '10512',
    '이름' : '김하늘',
    '학년' : 1,
    '동아리' : 'AI연구부',
    '역할' : '부원'
}])

modi_file = pd.concat([df, add_df], ignore_index=True)
modi_file.to_excel('new_club.xlsx', index=False)

modi_file

      학번   이름  학년     동아리  역할
0  10401  이민호   1  AI 연구부  부장
1  10405  박서연   1  AI 연구부  부원
2  10503  최지우   1  AI 연구부  부원
3  10512  김하늘   1   AI연구부  부원